name: WGChestRefillFlag
description: Auto-refilling functionality for containers within WorldGuard regions
version: 0.1c
load: postworld
authors: [Martin Ambrus]
softdepend: []
depend: [WorldGuard]
main: com.martinambrus.wgchrf.WGChestRefillFlagPlugin