name: WGChestRefillFlag
description: Auto-refilling functionality for containers within WorldGuard regions
version: 0.1b
load: postworld
authors: [Martin Ambrus]
softdepend: []
depend: [WorldGuard, WGCustomFlags]
main: com.martinambrus.wgchrf.WGChestRefillFlagPlugin